### PR TITLE
Add support for bone collections in Blender 4.0

### PR DESCRIPTION
**Pull request by slbelden**
Adds version check for 3.6 and lower in common utils.
Changes calls from bone layers to bone collections for 4.0 and higher.

### CODE REVIEW

**Comment by Flynsarmy** [comment]
You forgot to import the `version_3_6_or_older()` function on line 11 of *tools/armature.py*

**Comment by slbelden** [comment]
What do you mean? It’s imported on line 12.

IMG_4527

**Comment by Flynsarmy** [comment]
Ah, mb. I was on the Files Changed tab and missed it somehow. Thanks for the PR it helped me a lot!

**Comment by slbelden** [comment]
PR closed in favor of #648

**Pull request closed without merging**
