### PR TITLE
 Fix Material blend in viewport

### PR DESCRIPTION
**Pull request by 989onan**
People would complain that their transparent materials looked like garbage after fix model. This fixes it.
(let's try this pull request again)

### CODE REVIEW

**Comment by feilen** [comment]
A tip if you wanna clean up your commits to make the push clearer: if you do `git rebate -I HEAD~10` or so, you can selectively pick what gets omitted/squashed/etc, then push-f to your tracking branch on github.

**Comment by 989onan** [comment]
thanks! I'll keep that in mind since I have almost never used github before

**Comment by 989onan** [comment]
I just tried a squash on development branch, and it says it's up to date

**Comment by feilen** [comment]
Looks like this ended up in the other pull request

**Pull request closed without merging**
