### PR TITLE
Add Bake Texture Quality Settings and many Bake optimisations and bug fixes

### PR DESCRIPTION
**Pull request by Mysteryem**
This pr grew a bit out of control as I kept finding more bugs to replace the ones I fixed. I think it's a good time for a break, so I've left it as separate commits for now and I, or someone else, can squash it all later if needed. Let me know of any issues.

New features:
1. Texture Quality (samples) dropdown
    - 4 options to choose from:
    - High: Same behaviour as the Bake Button before 
    - Low: 1/4 the number of samples as High. I find it bakes in about half the time as High and I honestly can't tell the difference between the two
    - Lowest: Intended as a much quicker and lower quality preview. Every pass set to 1 sample, except AO which is set to 4, because it looks really really bad with less than that
    - Custom (advanced): Displays sliders for all of the enabled passes, soft-capped between the samples of Lowest Quality and the samples of High Quality, though any integer greater than zero can be typed in
    - image
    - image

Improvements/changes (mostly replacing iteration of large lists with numpy and using foreach_get and foreach_set methods):
1. Massive performance increase for code that reads and writes pixels. Painstakingly slow is an understatement for the old code trying to copy, update and iterate through the pixels of 4096x4096 images
    - Pretty much everything that touched image.pixels has been entirely replaced
3. Optimised UNMIRROR and MANUAL uv overlap correction
    - uvs retreived and updated directly with foreach_get and foreach_set
5. Optimised optimize_solid_materials
    - No more swapping in and our of edit mode
    - No more iterating through the polygons to get the loop_indices
6. Optimised face prioritisation
7. Organised the settings for each of the bake passes into one place instead of strewn across the code wherever the bake_pass function is called
6. Moved conditional checks outside of a bunch of for loops so the conditions are only evaluated once (or fewer times for nested loops) instead of every loop
8. Added a contextmanager decorated function for temporarily unlinking BSDF input nodes and replacing their default_values, automatically restoring the links and default_values once done
9. Iteration of bake_<bake_name> shader value nodes now also iterates through all group nodes
10. Prop bone generation now finds all the vertex groups that have a corresponding bone ahead of time, and only counts and searches for those vertex groups
11. Bake duration added to terminal output

Fixes:
1. GMOD specific directories attempt to be created even when the export type is not GMOD
12. Polygons belonging to solid materials when optimize_solid_materials is enabled are uv unwrapped when they shouldn't be
13. Solid colour square creation mistakenly re-copies the entire image every time a new solid colour square is added
14. Shape keys with the same name in multiple meshes get restored to the same value after being temporarily disabled during shape key baking
15. Non 1.0 alpha messes up diffuse bakes
    - Would multiply with the colour making the bake too dark
17. 0.0 alpha messes up roughness bakes
    - Areas of exactly zero alpha would end up with zero smoothness
19. Some passes erase the original values of lesser used BSDF inputs without restoring them
20. Color texture's rgb are multiplied by their alpha channel during bakes resulting in much darker bakes on transparent areas
22. Iteration of bake_<bake_name> shader nodes only checks the active material of each object
23. Creating or repurposing the image texture node that will be baked to and setting it as active is mistakenly done once for every shader node
24. optimize_solid_materials errors when a material slot is empty
25. optimize_solid_materials counts the same solid material multiple times, resulting in the wrong index and placing uvs in the wrong place
26. Prop bone generation errors when a candidate vertex group has no corresponding bone
27. The non-indirect emit pass is missing its solidmaterialcolors argument
28. The indirect emit pass is missing the 'GLOSSY' Blender bake pass resulting in indirect emission being dimmer than it should be (maybe this was done on purpose? It seems to be an odd omission to me)
29. Non 1.0 alpha messes up emission bakes
    - Would multiply with the colour making the bake too dark
30. Solid colour emission causes the entire material to be considered a solid colour for optimize_solid_materials, even if the other passes are not solid

Issues still present:
1. LOD Add/Delete buttons error when clicked
2. Image sharpening occurs after solid material optimisation, causing artifacting on the solid colour squares
3. Enabling specular setup, changing normal alpha to specular and then disabling specular setup causes an error during bake when it still tries to pack specular in normal alpha even though specular is disabled
4. object.show_only_shape_key ('shape key pinning') most likely breaks everywhere that relies on new shape keys created from a specifically set up current mix
   - No idea who would use this, but handling it properly would make the code more robust

General performance and tidiness notes from having worked on this existing code:
1. If an expression can be done outside of a loop, do so instead of re-evaluating the expression in every loop
2. uvs in UV layers can be iterated directly, there's no need to iterate through all the polygons to iterate through all the loop_indices to get uvs by subscripting the uv_layer with each loop index
3. If there's a way to do something with an operator and there's a way to it without, the operator is almost always slower
    - e.g. use object.shape_key_add instead of bpy.ops.object.shape_key_add
4. Avoid going in and out of edit mode as much as possible, if you can manipulate the data directly in Object mode, it's usually faster.
4. DRY: Don't Repeat Yourself
    - There were a boatload of list comprehensions creating the exact same list, if it's not going to be modified, use the same list over and over (or use a tuple so you can guarantee that it can't be modified)
6. If you're adding, subtracting, multiplying and modulus-ing integers together, the result is always going to be an integer.
    - You can use `//` for integer division instead of int(a/b)
7. If you need to iterate through a big list to find things and then need those things for something later on, don't iterate through that big list a second time, store those things in their own list when you find them the first time and get them from that new list when you need them again
8. I'm not well versed on Python's garbage collector, but I think that if you have a ginormous function that takes ages, e.g. perform_bake, none of the variables are going to go out of scope and be garbage collected until the function returns or the variables are overwritten or deleted with `del`.
    - A list containing all the pixels of a single 4096x4096, 4 channel image stored as 32bit floats is 256MB of data that could be sitting around doing nothing until the function returns. (a 2048x2048 image would be 64MB instead)
    - Splitting up the code into separate functions that do one job only would be my preference, but I didn't want to completely obliterate the structure of the original code with the changes here

### CODE REVIEW

**Comment by feilen** [comment]
Neat, thanks for the fixes!

> Texture Quality (samples) dropdown 

I'm still a bit wary of having more than two presets here. Generally speaking I've been less concerned about the performance of the actual baking process, in lieu of spending time on more features to make the end result more performant. Any bit helps though! 

> Massive performance increase for code that reads and writes pixels. Painstakingly slow is an understatement for the old code trying to copy, update and iterate through the pixels of 4096x4096 images 

I would generally discourage using 4k textures for... just about anything that's going into a realtime engine, but you do you! The bake passes are always going to be the heaviest steps. Incidentally, I see you added a time measurement, did you happen to get any before/after times for performance?

> Non 1.0 alpha messes up diffuse bakes; 0.0 alpha messes up roughness bakes 

I've been meaning to switch all of these misc passes to use the Emit channel instead, since that seems to be the convention in other bake-related projects I've seen.

> The indirect emit pass is missing the 'GLOSSY' Blender bake pass resulting in indirect emission being dimmer than it should be (maybe this was done on purpose? It seems to be an odd omission to me)

Glossy is viewport-dependent, and generally relates less to emission and more to phong/rim-lighting. Generally speaking it's a bad idea to bake glossiness except as a general color pass.

> DRY: Don't Repeat Yourself 

On a personal note, you might just consider that we haven't had a lot of spare time to optimize. Giving us extremely basic programming advice isn't a particularly polite approach...

> If you're adding, subtracting, multiplying and modulus-ing integers together, the result is always going to be an integer.

2.5 x 100.0 is 250, but int(2.5) * int(100.0) is 200. In general you shouldn't discard precision until the absolute last minute.

> You can use // for integer division instead of int(a/b)

See above. This is also unlikely to make a enormous performance difference unless you are using PyPy, as in Python you generally don't get loop-vectorization or other goodies. Floating point operations technically take more CPU cycles, but on non-MIP architectures which use cache lines, you usually have to do some extra work to make sure you're actually loading everything into the same cache lines. Numpy might take advantage though, I would have to do some digging.

> If you need to iterate through a big list to find things and then need those things for something later on, don't iterate through that big list a second time, store those things in their own list when you find them the first time and get them from that new list when you need them again

Again, we simply haven't had a lot of spare time to optimize.

I'm a bit wary of pulling in the floating point changes, but I'll try to find time before next release to go over the rest!

**Comment by Mysteryem** [comment]
> I'm still a bit wary of having more than two presets here. Generally speaking I've been less concerned about the performance of the actual baking process, in lieu of spending time on more features to make the end result more performant. Any bit helps though!

Personally, I would be inclined to make Low Quality the default number of samples and remove High Quality because I don't think it's necessary to bake with so many samples.

> I would generally discourage using 4k textures for... just about anything that's going into a realtime engine, but you do you! The bake passes are always going to be the heaviest steps. Incidentally, I see you added a time measurement, did you happen to get any before/after times for performance?

I would've said that a 4k atlas for an entire avatar plus clothes is very normal if it's fully textured. Sometimes I can squeeze everything into 2k, but I find it's usually not quite enough and then I may as well fill out the rest of the 4k texture. Knowing the vrchat crowd, I would expect quite a few people trying to bake 8k textures too; much to my displeasure.

Anyway, some timings and the two sets of Bake settings use:
image
image
image


> On a personal note, you might just consider that we haven't had a lot of spare time to optimize. Giving us extremely basic programming advice isn't a particularly polite approach...

It may be extremely basic programming advice, but such extremely basic issues shouldn't exist in the first place in my opinion. There's more to DRY than just not having lots of the same copy-pasted code which may not always be applicable, but this was a failure of the most extreme programming basics.

If it was only once that this happened I wouldn't have said anything, but it happened multiple times with the offending duplicate code right next to the other duplicates. There are still a bunch more duplicate iterations of lists of objects that check the same conditions that could be changed to use the same variable, but they're much more spread out and I didn't change them. It may be wasteful, but realistically there's no performance concern since the number of iterations are so few. The main reason is that it makes it annoying to modify the code since each duplicate needs to be updated separately for any changes instead of only a single variable.
> 2.5 x 100.0 is 250, but int(2.5) * int(100.0) is 200. In general you shouldn't discard precision until the absolute last minute.
[...]
> See above. This is also unlikely to make a enormous performance difference unless you are using PyPy, as in Python you generally don't get loop-vectorization or other goodies. Floating point operations technically take more CPU cycles, but on non-MIP architectures which use cache lines, you usually have to do some extra work to make sure you're actually loading everything into the same cache lines. Numpy might take advantage though, I would have to do some digging.

My meaning behind this comment is that there were a bunch of input values that were always integers and then a bunch of math operations were done on them with multiple unnecessary conversions to int when all of the values were guaranteed to be ints anyway.

Leaving in all of the conversions to int implies that some of the input values are not integers, when this was not the case. It's not meant to be a comment on performance, but one on clarity and maintainability, and to me, it looked like whoever had written it might not have know that the `//` operator is a thing. Coming from strongly typed languages before using python, it wasn't something I realised was a thing right away.

> I'm a bit wary of pulling in the floating point changes, but I'll try to find time before next release to go over the rest!

Could you elaborate on this?

If this is to do with reading pixels as np.single, image.pixels.foreach_get(buffer) actually rejects buffers that don't have the correct typing, so I assume single is the correct precision of the data at least. I haven't looked into the corresponding code in the blender source for this one, but can if you want.

foreach_get(attribute, buffer) on the other hand does support buffers with a different type to the data, though has to iterate over all the data in C and cast to the type of the buffer if it doesn't match, which is of course slower than a direct copy of data. I have a custom build of blender that gives a warning if I foreach_get(attribute, buffer) with an incorrectly typed buffer, so the buffers used should all be the correct type.

**Comment by feilen** [comment]
> I would've said that a 4k atlas for an entire avatar plus clothes is very normal if it's fully textured. Sometimes I can squeeze everything into 2k, but I find it's usually not quite enough and then I may as well fill out the rest of the 4k texture.

That level of detail is going to be extremely hard to be close enough to see (well, depending on what you purpose your avatar for). 99% of the time people are going to be seeing a lower mipmap, so it's better to focus efforts on making the mipmaps sharper. Bake isn't really aiming for so much of an atlas as a platform-optimized variant of a model.

> It may be extremely basic programming advice, but such extremely basic issues shouldn't exist in the first place in my opinion. 

_Regardless_ of your opinions on the matter, if you're expecting that I'm going to take additional time to review your request, you can't expect that I will decide to if you're rude. Engineering is mostly talking to people, and the further up in seniority you get, the more talking it becomes.

**Comment by Mysteryem** [comment]
> That level of detail is going to be extremely hard to be close enough to see (well, depending on what you purpose your avatar for). 99% of the time people are going to be seeing a lower mipmap, so it's better to focus efforts on making the mipmaps sharper. Bake isn't really aiming for so much of an atlas as a platform-optimized variant of a model.

Stylised avatars lose out a lot if drawn on lines and other details lose their sharpness, though I will agree that you can get away with lower resolution textures for more realistic models where there isn't a stylised look to maintain.

Additionally, I don't see what Bake has to do with making sharper mipmaps? If anything, compared to an atlas, I would think it results in blurrier mipmaps, since an atlas is divided equally into binary divisions and unity's default mipmap generation does not blur across the boundaries of separate binary divisions, meaning you can avoid separately coloured areas blurring together until the mipmaps get much smaller.

While I think a lot of purpose behind Bake is to allow for easier creation of variants of models that can be used to create valid fallback avatars for PC and Quest VRChat, I think that another important purpose is allowing easy creation of more optimised models (but not necessarily to the extent of a fallback avatar) from originally very poorly optimised models with far too many separate materials and textures whereby the level of detail from the original unoptimised avatar would be expected to be maintained to a similar level. In particular, it is common for Very Poor and sometimes Poor ranked VRChat avatars to be banned from events and Bake offers a good solution for those whose avatar performance ranking is from having too many separate meshes and materials.

> Regardless of your opinions on the matter, if you're expecting that I'm going to take additional time to review your request, you can't expect that I will decide to if you're rude. Engineering is mostly talking to people, and the further up in seniority you get, the more talking it becomes.

I don't expect anyone to be taking additional time to review this. I have written this code and will use it myself, you are free to take what you want from what I have written. I have attempted to arrange the commits such that this is easy to do. Neither of us owe the other anything. This is not a business that I am a part of, I'm not getting paid and I don't expect as such.

My complaint comes from the fact that basic mistakes have made it into live code (the development branch is regularly recommended to people trying to use the current Blender version that are having issues with Cats), somewhere along the lines, someone has failed to prevent such code entering the codebase.

If you want people to contribute to this project then I think stricter requirements for, or better reviews of contributed code are necessary so that contributors don't have to spend additional time cleaning up the existing code before they can even start working on their contributions. People are going to be less likely to want to help out if they can immediately see that there are clear, basic issues, which is shooting yourself in the foot as an open source project.

**Comment by 989onan** [comment]
"Polygons belonging to solid materials when optimize_solid_materials is enabled are uv unwrapped when they shouldn't be": This needs to be done since UV's can just not have UV data... I have gotten that error before.

"General performance and tidiness notes from having worked on this existing code:": All of these are good actually, but sometimes this can happen:
Let's just say we have a list of 10,000,000 items:
Person one rewrites the list as rows of four and crosses out the 3rd column.
Person two crosses out every 3rd item and is given a tool to block out 3 numbers at a time so they can focus on every 4th number.
Which one would be faster?
Well in terms of assembly and for statements, Person two would be faster since for statements can natively increase by 3 with 0 impact on performance compared to iterating through a list one at a time. It's like using a while(i<arraylength){ i += 3} which is actually very fast
That means, reshaping an array just to grab one column or multiple columns is actually *worse* than just iterating through it manually. If a python compiler has at least 2 brain cells it would be able to make it faster than numpy reshape
Only reason why reshape is really used is for putting it into other functions that take it or for representation of data, not iterating through a flattened matrix of 4XInfinity

**Comment by 989onan** [comment]
> 

Also, I mean iterate by 4 and minus the current iteration by 4 by 1 to get the 3rd column

**Comment by feilen** [comment]
> Additionally, I don't see what Bake has to do with making sharper mipmaps?

My point is mostly that, you will almost never see MIP0 in VR if your texture is 2k, 4k is overkill for most things using a headset. Not particularly related to this change beyond performance considerations.

> This is not a business that I am a part of, I'm not getting paid and I don't expect as such.

I am also doing this for free in my spare time, and I'm not going to consider this change if it means forgoing basic civility. Would you be interested in a change if someone lead with those comments? You can still be polite, even if you have concerns.

Closing for now.

**Comment by Mysteryem** [comment]
> That means, reshaping an array just to grab one column or multiple columns is actually worse than just iterating through it manually.

If this is to do with reshaping of numpy's ndarrays, changing the shape actually has no effect on the data itself in memory, it changes how the data is viewed, which is more like changing how numpy interprets how you are accessing the data. Admittedly, yes, this can change the speed at which writes and reads are made, since numpy will have to adjust for the current shape and how you're slicing/indexing the array to access its elements. You could figure out the correct indices for reading and writing the data for specific pixels of a 2d image stored in a flat array and you might get a small time save if it's faster for you to calculate the indices yourself instead of letting numpy do it for you. But I don't think there is significant enough of a time save to be made there (and possibly not any) that would be worth it over being able to represent the human view of the data more clearly in code, i.e. by treating the pixels of an rgba image as if it were a 3d array of [width][height][rgba(4)] instead of the flat width * height * rgba length array that it is in memory.

Setting ndarray.shape enforces that the new shape can still represent the same contiguous data in memory, raising an error if the shape is not possible, this is opposed to the ndarray.reshape/numpy.reshape functions which will create a view of the data if possible, but, unlike changing ndarray.shape, will copy the array if the desired new shape is not possible.

Taking slices of ndarrays also produce views of the data without copying or changing any of the data in memory, I've tried to make it clear in the code by appending all such variables that are views with _view. The only real disadvantage with views is that they keep a reference to the full array, meaning that if you only need a tiny part of a huge array and need to keep it around for a long time, you'll want to make sure to copy that tiny part into a new array so the huge array it referenced can be garbage collected.

As a side note, I find that iterating through flat numpy arrays one element at a time is actually rather slow, you're better off using a python array from the array module if you need to work with a specific type or using a plain old python list

**Comment by Mysteryem** [comment]
> I am also doing this for free in my spare time, and I'm not going to consider this change if it means forgoing basic civility. Would you be interested in a change if someone lead with those comments? You can still be polite, even if you have concerns.
> Closing for now.

Honestly, I don't know what you want me to say, I saw a bunch of code making some basic mistakes and described the issue exactly as I saw it:
> DRY: Don't Repeat Yourself
> There were a boatload of list comprehensions creating the exact same list, if it's not going to be modified, use the same list over and over (or use a tuple so you can guarantee that it can't be modified)

I don't think there's anything unpolite about this, I didn't say it was bad code or that the person who wrote it was a bad programmer, I didn't even bother checking who wrote any of the code and I still don't know. Who would I be to make assumptions about the skill levels of the contributors? Whether the person who wrote it is new to programming or is a software development professional, there was a failure of some of the basics and I pointed it out as I don't think such failures have a place in a live branch which should be reviewed to prevent such issues from making it into the code. I don't understand how I'm expected to describe the issue here in a more polite manner than I did above:
image

**Pull request closed without merging**
