### PR TITLE
Fixes breakage with fix model

### PR DESCRIPTION
**Pull request by 989onan**
Fixes breakage with fix model when hitting the fix button and the model armature is not under any collections. This patches that by adding a new collection and throwing everything under that.

### CODE REVIEW

**Comment by Mysteryem** [comment]
Are you sure this fixes whatever the issue is here?

As far as I can tell, `armature` here comes from `armature = Common.set_default_stage()` which gets the armature through `armature = get_armature()`, which gets the first armature object in `get_objects()` with name matching `bpy.context.scene.armature` (or first armature object if `bpy.context.scene.armature` is a Falsey value such as `''`). `get_objects()` finds only objects in `bpy.context.view_layer.objects` (for Blender 2.80+). From this, we can say that `armature` must be in the current view_layer and therefore, must be in a collection and therefore `parentcollectionname = armature.users_collection[0].name` will never raise an exception from being out of bounds (unless some of the previous code between here and `armature = Common.set_default_stage()` has removed it from all collections for some reason, in which case, why?).

Additionally, all of this code using collections needs to be surrounded with `if not version_2_79_or_older():` as Blender 2.79 does not have collections.

**Comment by Mysteryem** [comment]
Ok. If this is related to 
image
then that's because the `scene` variable used in `scene.collection.children.link(coll)` has not been defined.

Though, from my previous comment, this appears odd, as this line of code is only executed when `coll = bpy.data.collections.get(name)` is a Falsey value, but I've just said that as far as I can tell `armature` will always be in a collection.

What can happen, and what I think is happening, is that `armature` is in the "Scene Collection". If you attempt to get the name of the "Scene Collection" you will get `'Master Collection'`. There is no bpy.data.collections['Master Collection'] as the collection is part of the scene and is not a separate collection that can be found in bpy.data.collections.

**Comment by 989onan** [comment]
People can import their model outside of a collection. This is only to fix an issue that they had which was solved by exactly just putting the armature inside a collection. That error message and stuff is unrelated to this fix.

**Comment by 989onan** [comment]
If we need to fix another issue, then a new pull request would be easiest.

**Comment by Mysteryem** [comment]
My point is that you're saying the issue is when an armature is not in a collection, but the `armature` must *always* be in a collection as per my first comment, unless some of the code after `armature = Common.set_default_stage()` is removing it from all collections and thus removing it from the scene, in which case, fix that problem instead of putting a band aid on top of what the actual problem is.

**Comment by 989onan** [comment]
yeah okay if there is something that's supposed to fix what my code is fixing (putting it in a collection if it wasn't already in a collection before clicking fix model) then yes, we should do a different pull request to fix that and close this one

**Comment by Mysteryem** [comment]
Can you at least provide more information on what the issue actually is and provide steps to reproduce it? What do you expect to happen and what actually happens? Is there an open issue with more information?

**Comment by 989onan** [comment]
"Fixes breakage with fix model when hitting the fix button and the model armature is not under any collections. This patches that by adding a new collection and throwing everything under that."

This is what causes the issue, put an armature for a model not under a collection. Hit fix model, error occurs. I expect no error. And I haven't seen one before this issue

**Comment by Mysteryem** [comment]
> "Fixes breakage with fix model when hitting the fix button and the model armature is not under any collections. This patches that by adding a new collection and throwing everything under that."
> 
> This is what causes the issue, put an armature for a model not under a collection. Hit fix model, error occurs. I expect no error. And I haven't seen one before this issue

But if you remove the armature from all collections, it's no longer in the view layer of the scene and is effectively orphan data and it won't be available for Cats to detect, meaning you can't even hit the fix model button.

**Comment by 989onan** [comment]
It's under scene collection and not in a collection under scenes. It's still in the scene. It happens with some importers like Blender Source Tools by default

**Comment by Mysteryem** [comment]
> It's under scene collection and not in a collection under scenes. It's still in the scene. It happens with some importers like Blender Source Tools by default

So the armature is still in a collection.

Yes, fix model is currently broken in the case that the Armature is in the Scene Collection because the current code tries to find the Scene Collection in bpy.data.collections, which does not contain scene collections, so it thinks the Armature is not in a collection (bug 1),
and then runs code to add it to a new collection, but that code contains an undeclared 'scene' variable (bug 2).

This PR fixes neither of these bugs, the code still tries to get the collection from bpy.data.collections (`bpy.data.collections.get(parentcollectionname)`), which will return `None` if the collection is a scene collection, and still contains the undeclared 'scene' variable (`scene.collection.children.link(coll)`), so what does it fix?

If you try to Fix Model with the code in this PR and an armature in the Scene Collection, it still gives you the NameError because the 'scene' variable is not defined. (This is run with the changed code in this PR)
image
image

**Comment by 989onan** [comment]
yes, which is why your solution works

**Comment by 989onan** [comment]
closed due to #435

**Pull request closed without merging**
